### ISSUE TITLE
Clarify namespaces in reference docs

### ISSUE THREAD

**Issue by bdpedigo** [CAVEconnectome/nglui#51]
<img width="1345" alt="Screenshot 2024-11-12 at 2 53 24 PM" src="https://github.com/user-attachments/assets/6ade20d0-e721-4c28-831b-a3497dc3efc3">

currently there is nothing in the docs here to indicate that `make_neuron_neuroglancer_link` is not in the same namespace as `make_point_statebuilder` etc.

**Comment by ceesem** [comment]
Fixed in docs, thanks!
