### ISSUE TITLE
mismatch in identifying target_site from url prefix in statebuilder

### ISSUE THREAD

**Issue by bpdanskin** [CAVEconnectome/nglui#55]
Generating a spelunker link with statebuilder no longer adds the correct middleauth to the segmentation source. The following worked previously: 
```
img, seg = from_client(client)
ngl_url = "https://spelunker.cave-explorer.org/"

img_layer = ImageLayerConfig(name='img',
                             source=img.source,
                             )

seg_layer = SegmentationLayerConfig(name = 'seg',
                                    source = seg.source,
                                    alpha_3d=0.8,
                                   )

sb = StateBuilder(layers=[img_layer, seg_layer], 
                  client=client, 
                  url_prefix="https://spelunker.cave-explorer.org/",
                 )
sb.render_state(return_as='html')
```
[Neuroglancer Link](https://spelunker.cave-explorer.org/#!%7B%22jsonStateServer%22:%22https://global.daf-apis.com//nglstate/api/v1/post%22,%22navigation%22:%7B%22pose%22:%7B%22position%22:%7B%22voxelSize%22:%5B4.0,4.0,40.0%5D%7D%7D,%22zoomFactor%22:1.0%7D,%22showSlices%22:false,%22layout%22:%22xy-3d%22,%22perspectiveZoom%22:5000.0,%22layers%22:%5B%7B%22type%22:%22image%22,%22source%22:%22precomputed://https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/minnie65/em%22,%22name%22:%22img%22%7D,%7B%22type%22:%22segmentation_with_graph%22,%22source%22:%22graphene://https://minnie.microns-daf.com/segmentation/table/minnie3_v1%22,%22selectedAlpha%22:0.3,%22objectAlpha%22:0.8,%22notSelectedAlpha%22:0.0,%22name%22:%22seg%22%7D%5D%7D)

The segmentation layer fails to load with a HTTP error 401. The following works as intended:
```
img, seg = from_client(client)
ngl_url = "https://spelunker.cave-explorer.org/"

img_layer = ImageLayerConfig(name='img',
                             source=img.source,
                             )

seg_layer = SegmentationLayerConfig(name = 'seg',
                                    source = seg.source,
                                    alpha_3d=0.8,
                                   )

sb = StateBuilder(layers=[img_layer, seg_layer], 
                  client=client, 
                  # url_prefix="https://spelunker.cave-explorer.org/",
                  target_site='spelunker',
                 )
sb.render_state(return_as='html')
```
[Neuroglancer Link](https://spelunker.cave-explorer.org/#!%7B%22dimensions%22:%7B%22x%22:%5B4e-09,%22m%22%5D,%22y%22:%5B4e-09,%22m%22%5D,%22z%22:%5B4e-08,%22m%22%5D%7D,%22showSlices%22:false,%22layout%22:%22xy-3d%22,%22crossSectionScale%22:1.0,%22projectionScale%22:5000.0,%22layers%22:%5B%7B%22type%22:%22image%22,%22source%22:%5B%7B%22url%22:%22precomputed://https://bossdb-open-data.s3.amazonaws.com/iarpa_microns/minnie/minnie65/em%22%7D%5D,%22name%22:%22img%22%7D,%7B%22type%22:%22segmentation%22,%22source%22:%5B%7B%22url%22:%22graphene://middleauth+https://minnie.microns-daf.com/segmentation/table/minnie3_v1%22%7D%5D,%22selectedAlpha%22:0.3,%22objectAlpha%22:0.8,%22notSelectedAlpha%22:0.0,%22name%22:%22seg%22%7D%5D%7D)
with or without url_prefix. But the target site lookup from url_prefix seems to have broken

**Comment by ceesem** [comment]
Fixed in 3.6.2, thanks!
