### ISSUE TITLE
documentation misnames site_config option

### ISSUE THREAD

**Issue by bpdanskin** [CAVEconnectome/nglui#58]
On documentation page: https://caveconnectome.github.io/nglui/usage/config/
```
from nglui import site_config, statebuilder

site_config.get_default_config()
```

should be

```
from nglui import site_utils, statebuilder

site_utils.get_default_config()
```

same for all uses of `site_config` on the page. Code otherwise works as intended

Edit to add: nglui version 3.6.2

**Comment by bpdanskin** [comment]
Also, this errors with wrong argument name:
```
site_utils.set_default_config(datastack=CAVEclient('minnie65_public'))
```
and the following does not error, but does not change the config defaults appropriately:
```
site_utils.set_default_config(datastack_name='minnie65_public')

**Comment by ceesem** [comment]
Fixed! Thank you
