### ISSUE TITLE
unable to generate state off default_config with helper functions

### ISSUE THREAD

**Issue by bpdanskin** [CAVEconnectome/nglui#59]
high-level statebuilders functions fail to consistently load the default config options when generating neuroglancer states, leading to 401 errors on segmentation sources or other failed neuroglancer states. 
nglui version: 3.6.2
```
from caveclient import CAVEclient
from nglui.statebuilder import helpers
from nglui import site_utils

datastack_name = "minnie65_public"
client = CAVEclient(datastack_name)

materialization = 1181 
client.version = materialization
```
Default site config is for seunglab. However, the two helper functions `make_neuron_neuroglancer_link` and `make_synapse_neuroglancer_link` generate spelunker links by default, with the following:
```
rids = [864691135463492421]
ngl_url = helpers.make_neuron_neuroglancer_link(client, rids, return_as="url")
```
yielding https://spelunker.cave-explorer.org/#!middleauth+https://global.daf-apis.com/nglstate/api/v1/6590762062970880
which has 401 error on segmentation due to the missing oauth. 

Specifying target_site as `mainline` or `spelunker` or `cave-explorer` generate working spelunker links:
```
site_utils.set_default_config(target_site='spelunker')

# or

ngl_url = helpers.make_neuron_neuroglancer_link(client, rids, return_as="url", target_site='cave-explorer')
```
However, specifying 'seunglab' fails to generate a working neuroglancer state:
```
site_utils.set_default_config(target_site='seunglab')

# or

ngl_url = helpers.make_neuron_neuroglancer_link(client, rids, return_as="url", target_site='seunglab')
```
https://spelunker.cave-explorer.org/?json_url=https://global.daf-apis.com/nglstate/api/v1/6357920758366208

**Comment by ceesem** [comment]
This should be fixed in 3.7.0, just out on pypi now.
